const CATEGORIES = [
  { id: "games", name: "Игры", icon: "🎮" },
  { id: "messengers", name: "Мессенджеры", icon: "💬" },
  { id: "social", name: "Социальные сети", icon: "📱" },
  { id: "music", name: "Музыка", icon: "🎵" },
  { id: "video", name: "Видео", icon: "🎬" },
  { id: "ai", name: "Искусственный интеллект", icon: "🤖" },
  { id: "education", name: "Образование", icon: "📚" },
  { id: "utilities", name: "Утилиты", icon: "🛠" },
  { id: "photo", name: "Фото и видео", icon: "📷" },
  { id: "finance", name: "Финансы", icon: "💰" },
  { id: "shopping", name: "Покупки", icon: "🛒" },
  { id: "navigation", name: "Навигация", icon: "🗺" },
  { id: "security", name: "Безопасность", icon: "🔐" },
  { id: "work", name: "Работа", icon: "💻" },
  { id: "design", name: "Дизайн", icon: "🎨" },
  { id: "programming", name: "Программирование", icon: "👨‍💻" },
  { id: "popular", name: "Популярное", icon: "⭐" },
  { id: "new", name: "Новинки", icon: "🆕" }
];

const APPS = [
  {
    id: "telegram",
    name: "Telegram",
    developer: "Telegram FZ-LLC",
    category: "messengers",
    categories: ["messengers", "popular"],
    description: "Быстрый и безопасный мессенджер. Облачные чаты, каналы, боты, голосовые сообщения и звонки.",
    fullDescription: "Telegram — один из самых популярных мессенджеров в мире. Поддерживает секретные чаты, большие группы, каналы, ботов, стикеры, голосовые и видеозвонки.",
    icon: "https://upload.wikimedia.org/wikipedia/commons/8/82/Telegram_logo.svg",
    platforms: ["ios", "android", "web"],
    rating: 4.8,
    version: "11.x",
    size: "~100 МБ",
    updated: "2026",
    links: {
      ios: "https://apps.apple.com/app/telegram-messenger/id686449807",
      android: "https://play.google.com/store/apps/details?id=org.telegram.messenger",
      web: "https://web.telegram.org",
      official: "https://telegram.org"
    },
    free: true,
    popular: true
  },
  {
    id: "whatsapp",
    name: "WhatsApp",
    developer: "Meta Platforms",
    category: "messengers",
    categories: ["messengers", "popular"],
    description: "Простой и надёжный мессенджер от Meta. Сообщения, звонки, статусы, группы.",
    fullDescription: "WhatsApp Messenger позволяет обмениваться сообщениями, совершать голосовые и видеозвонки. End-to-end шифрование по умолчанию.",
    icon: "https://upload.wikimedia.org/wikipedia/commons/6/6b/WhatsApp.svg",
    platforms: ["ios", "android", "web"],
    rating: 4.6,
    version: "2.x",
    size: "~80 МБ",
    updated: "2026",
    links: {
      ios: "https://apps.apple.com/app/whatsapp-messenger/id310633997",
      android: "https://play.google.com/store/apps/details?id=com.whatsapp",
      web: "https://web.whatsapp.com",
      official: "https://www.whatsapp.com"
    },
    free: true,
    popular: true
  },
  {
    id: "youtube",
    name: "YouTube",
    developer: "Google LLC",
    category: "video",
    categories: ["video", "popular"],
    description: "Смотрите видео, подписывайтесь на каналы, создавайте контент.",
    fullDescription: "YouTube — крупнейшая видеоплатформа. Миллиарды видео, прямые трансляции, Shorts, музыка и подкасты.",
    icon: "https://upload.wikimedia.org/wikipedia/commons/0/09/YouTube_full-color_icon_%282017%29.svg",
    platforms: ["ios", "android", "web"],
    rating: 4.5,
    version: "19.x",
    size: "~50 МБ",
    updated: "2026",
    links: {
      ios: "https://apps.apple.com/app/youtube-watch-listen-stream/id544007664",
      android: "https://play.google.com/store/apps/details?id=com.google.android.youtube",
      web: "https://www.youtube.com",
      official: "https://www.youtube.com"
    },
    free: true,
    popular: true
  },
  {
    id: "instagram",
    name: "Instagram",
    developer: "Meta Platforms",
    category: "social",
    categories: ["social", "photo", "popular"],
    description: "Фото, видео, Reels, Stories и общение с друзьями.",
    fullDescription: "Instagram — социальная сеть для обмена фотографиями и видео. Reels, Stories, прямые эфиры, сообщения.",
    icon: "https://upload.wikimedia.org/wikipedia/commons/e/e7/Instagram_logo_2016.svg",
    platforms: ["ios", "android", "web"],
    rating: 4.4,
    version: "350+",
    size: "~100 МБ",
    updated: "2026",
    links: {
      ios: "https://apps.apple.com/app/instagram/id389801252",
      android: "https://play.google.com/store/apps/details?id=com.instagram.android",
      web: "https://www.instagram.com",
      official: "https://www.instagram.com"
    },
    free: true,
    popular: true
  },
  {
    id: "tiktok",
    name: "TikTok",
    developer: "TikTok Pte. Ltd.",
    category: "social",
    categories: ["social", "video", "popular"],
    description: "Короткие видео, тренды, музыка и творчество.",
    fullDescription: "TikTok — платформа коротких вертикальных видео. Тренды, эффекты, музыка, прямые эфиры.",
    icon: "https://upload.wikimedia.org/wikipedia/en/a/a9/TikTok_logo.svg",
    platforms: ["ios", "android", "web"],
    rating: 4.5,
    version: "35+",
    size: "~150 МБ",
    updated: "2026",
    links: {
      ios: "https://apps.apple.com/app/tiktok/id835599320",
      android: "https://play.google.com/store/apps/details?id=com.zhiliaoapp.musically",
      web: "https://www.tiktok.com",
      official: "https://www.tiktok.com"
    },
    free: true,
    popular: true
  },
  {
    id: "minecraft",
    name: "Minecraft",
    developer: "Mojang / Microsoft",
    category: "games",
    categories: ["games", "popular"],
    description: "Песочница, где можно строить, выживать и исследовать бесконечные миры.",
    fullDescription: "Minecraft — культовая игра-песочница. Создавайте миры, выживайте, сражайтесь с мобами, стройте всё, что угодно.",
    icon: "https://upload.wikimedia.org/wikipedia/en/5/51/Minecraft_cover.png",
    platforms: ["ios", "android"],
    rating: 4.6,
    version: "1.21+",
    size: "~300 МБ",
    updated: "2026",
    links: {
      ios: "https://apps.apple.com/app/minecraft/id479516143",
      android: "https://play.google.com/store/apps/details?id=com.mojang.minecraftpe",
      official: "https://www.minecraft.net"
    },
    free: false,
    note: "Платное приложение. Официальная покупка в App Store / Google Play.",
    popular: true
  },
  {
    id: "chatgpt",
    name: "ChatGPT",
    developer: "OpenAI",
    category: "ai",
    categories: ["ai", "popular", "new"],
    description: "Искусственный интеллект для общения, написания текстов, кода и идей.",
    fullDescription: "ChatGPT от OpenAI — мощный ИИ-ассистент. Отвечает на вопросы, помогает с текстами, кодом, анализом и творчеством.",
    icon: "https://upload.wikimedia.org/wikipedia/commons/0/04/ChatGPT_logo.svg",
    platforms: ["ios", "android", "web"],
    rating: 4.8,
    version: "1.x",
    size: "~50 МБ",
    updated: "2026",
    links: {
      ios: "https://apps.apple.com/app/chatgpt/id6448311069",
      android: "https://play.google.com/store/apps/details?id=com.openai.chatgpt",
      web: "https://chat.openai.com",
      official: "https://openai.com/chatgpt"
    },
    free: true,
    popular: true
  },
  {
    id: "spotify",
    name: "Spotify",
    developer: "Spotify AB",
    category: "music",
    categories: ["music", "popular"],
    description: "Музыка, подкасты и плейлисты. Миллионы треков.",
    fullDescription: "Spotify — стриминговый сервис музыки и подкастов. Персональные рекомендации, плейлисты, офлайн-режим (по подписке).",
    icon: "https://upload.wikimedia.org/wikipedia/commons/1/19/Spotify_logo_without_text.svg",
    platforms: ["ios", "android", "web"],
    rating: 4.7,
    version: "8.x",
    size: "~100 МБ",
    updated: "2026",
    links: {
      ios: "https://apps.apple.com/app/spotify-music-and-podcasts/id324684580",
      android: "https://play.google.com/store/apps/details?id=com.spotify.music",
      web: "https://open.spotify.com",
      official: "https://www.spotify.com"
    },
    free: true,
    popular: true
  },
  {
    id: "netflix",
    name: "Netflix",
    developer: "Netflix, Inc.",
    category: "video",
    categories: ["video", "popular"],
    description: "Фильмы, сериалы и шоу. Смотрите онлайн и офлайн.",
    fullDescription: "Netflix — один из крупнейших стриминговых сервисов. Оригинальные сериалы, фильмы, документалки. Требуется подписка.",
    icon: "https://upload.wikimedia.org/wikipedia/commons/0/08/Netflix_2015_logo.svg",
    platforms: ["ios", "android", "web"],
    rating: 4.5,
    version: "8.x",
    size: "~80 МБ",
    updated: "2026",
    links: {
      ios: "https://apps.apple.com/app/netflix/id363590051",
      android: "https://play.google.com/store/apps/details?id=com.netflix.mediaclient",
      web: "https://www.netflix.com",
      official: "https://www.netflix.com"
    },
    free: false,
    note: "Требуется подписка Netflix.",
    popular: true
  },
  {
    id: "vk",
    name: "ВКонтакте",
    developer: "VK",
    category: "social",
    categories: ["social", "popular"],
    description: "Социальная сеть, музыка, видео, сообщения и сообщества.",
    fullDescription: "ВКонтакте — крупнейшая социальная сеть в русскоязычном сегменте. Друзья, сообщества, музыка, видео, мини-приложения.",
    icon: "https://upload.wikimedia.org/wikipedia/commons/2/21/VK.com-logo.svg",
    platforms: ["ios", "android", "web"],
    rating: 4.5,
    version: "5.x",
    size: "~120 МБ",
    updated: "2026",
    links: {
      ios: "https://apps.apple.com/app/vk-music-video-messenger/id564177498",
      android: "https://play.google.com/store/apps/details?id=com.vkontakte.android",
      web: "https://vk.com",
      official: "https://vk.com"
    },
    free: true,
    popular: true
  },
  {
    id: "discord",
    name: "Discord",
    developer: "Discord Inc.",
    category: "messengers",
    categories: ["messengers", "games", "popular"],
    description: "Голосовой и текстовый чат для геймеров и сообществ.",
    fullDescription: "Discord — платформа для общения в голосовых и текстовых каналах. Серверы, боты, стриминг экрана.",
    icon: "https://upload.wikimedia.org/wikipedia/en/9/98/Discord_logo.svg",
    platforms: ["ios", "android", "web"],
    rating: 4.5,
    version: "200+",
    size: "~100 МБ",
    updated: "2026",
    links: {
      ios: "https://apps.apple.com/app/discord-talk-play-hang-out/id985746746",
      android: "https://play.google.com/store/apps/details?id=com.discord",
      web: "https://discord.com/app",
      official: "https://discord.com"
    },
    free: true,
    popular: true
  },
  {
    id: "roblox",
    name: "Roblox",
    developer: "Roblox Corporation",
    category: "games",
    categories: ["games", "popular"],
    description: "Миллионы игр, созданных игроками. Играйте и создавайте.",
    fullDescription: "Roblox — платформа пользовательских игр и миров. Играйте в чужие проекты или создавайте свои.",
    icon: "https://upload.wikimedia.org/wikipedia/commons/3/3a/Roblox_player_icon_black.svg",
    platforms: ["ios", "android"],
    rating: 4.4,
    version: "2.x",
    size: "~200 МБ",
    updated: "2026",
    links: {
      ios: "https://apps.apple.com/app/roblox/id431946152",
      android: "https://play.google.com/store/apps/details?id=com.roblox.client",
      official: "https://www.roblox.com"
    },
    free: true,
    popular: true
  },
  {
    id: "duolingo",
    name: "Duolingo",
    developer: "Duolingo",
    category: "education",
    categories: ["education", "popular"],
    description: "Изучайте языки бесплатно. Уроки, игры и стрики.",
    fullDescription: "Duolingo — популярное приложение для изучения языков. Короткие уроки, геймификация, десятки языков.",
    icon: "https://upload.wikimedia.org/wikipedia/commons/1/15/Duolingo_logo.svg",
    platforms: ["ios", "android", "web"],
    rating: 4.7,
    version: "6.x",
    size: "~80 МБ",
    updated: "2026",
    links: {
      ios: "https://apps.apple.com/app/duolingo-language-lessons/id570060128",
      android: "https://play.google.com/store/apps/details?id=com.duolingo",
      web: "https://www.duolingo.com",
      official: "https://www.duolingo.com"
    },
    free: true,
    popular: true
  },
  {
    id: "notion",
    name: "Notion",
    developer: "Notion Labs",
    category: "work",
    categories: ["work", "utilities"],
    description: "Заметки, базы данных, вики и проекты в одном месте.",
    fullDescription: "Notion — универсальное рабочее пространство. Заметки, задачи, базы данных, документы и совместная работа.",
    icon: "https://upload.wikimedia.org/wikipedia/commons/4/45/Notion_app_logo.png",
    platforms: ["ios", "android", "web"],
    rating: 4.7,
    version: "0.x",
    size: "~50 МБ",
    updated: "2026",
    links: {
      ios: "https://apps.apple.com/app/notion-notes-docs-tasks/id1232780281",
      android: "https://play.google.com/store/apps/details?id=notion.id",
      web: "https://www.notion.so",
      official: "https://www.notion.so"
    },
    free: true
  },
  {
    id: "canva",
    name: "Canva",
    developer: "Canva",
    category: "design",
    categories: ["design", "photo"],
    description: "Дизайн для всех. Шаблоны, фото, видео и презентации.",
    fullDescription: "Canva — простой и мощный онлайн-редактор дизайна. Шаблоны для соцсетей, презентаций, постеров, видео.",
    icon: "https://upload.wikimedia.org/wikipedia/commons/0/08/Canva_icon_2021.svg",
    platforms: ["ios", "android", "web"],
    rating: 4.8,
    version: "2.x",
    size: "~100 МБ",
    updated: "2026",
    links: {
      ios: "https://apps.apple.com/app/canva-design-photo-video/id897446215",
      android: "https://play.google.com/store/apps/details?id=com.canva.editor",
      web: "https://www.canva.com",
      official: "https://www.canva.com"
    },
    free: true
  },
  {
    id: "signal",
    name: "Signal",
    developer: "Signal Foundation",
    category: "messengers",
    categories: ["messengers", "security"],
    description: "Приватный мессенджер с end-to-end шифрованием.",
    fullDescription: "Signal — мессенджер с сильным акцентом на приватность. Открытый исходный код, end-to-end шифрование по умолчанию.",
    icon: "https://upload.wikimedia.org/wikipedia/commons/8/8d/Signal-Logo.svg",
    platforms: ["ios", "android", "web"],
    rating: 4.6,
    version: "7.x",
    size: "~80 МБ",
    updated: "2026",
    links: {
      ios: "https://apps.apple.com/app/signal-private-messenger/id874139669",
      android: "https://play.google.com/store/apps/details?id=org.thoughtcrime.securesms",
      web: "https://signal.org",
      official: "https://signal.org"
    },
    free: true
  },
  {
    id: "github",
    name: "GitHub",
    developer: "GitHub / Microsoft",
    category: "programming",
    categories: ["programming", "work"],
    description: "Код, репозитории, Issues и Pull Requests в кармане.",
    fullDescription: "Официальное приложение GitHub. Просматривайте репозитории, Issues, Pull Requests, уведомления и код.",
    icon: "https://upload.wikimedia.org/wikipedia/commons/9/91/Octicons-mark-github.svg",
    platforms: ["ios", "android", "web"],
    rating: 4.6,
    version: "1.x",
    size: "~40 МБ",
    updated: "2026",
    links: {
      ios: "https://apps.apple.com/app/github/id1477376905",
      android: "https://play.google.com/store/apps/details?id=com.github.android",
      web: "https://github.com",
      official: "https://github.com"
    },
    free: true
  },
  {
    id: "claude",
    name: "Claude",
    developer: "Anthropic",
    category: "ai",
    categories: ["ai", "new"],
    description: "ИИ-ассистент от Anthropic. Безопасный и полезный.",
    fullDescription: "Claude — ИИ от Anthropic. Помогает с текстами, анализом, кодом и рассуждениями. Есть веб-версия и приложения.",
    icon: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/8a/Claude_AI_logo.svg/240px-Claude_AI_logo.svg.png",
    platforms: ["ios", "android", "web"],
    rating: 4.7,
    version: "1.x",
    size: "~40 МБ",
    updated: "2026",
    links: {
      ios: "https://apps.apple.com/app/claude-by-anthropic/id6473753684",
      android: "https://play.google.com/store/apps/details?id=com.anthropic.claude",
      web: "https://claude.ai",
      official: "https://claude.ai"
    },
    free: true,
    popular: true
  },
  {
    id: "capcut",
    name: "CapCut",
    developer: "Bytedance",
    category: "photo",
    categories: ["photo", "video", "popular"],
    description: "Мощный видеоредактор. Эффекты, шаблоны, музыка.",
    fullDescription: "CapCut — бесплатный видеоредактор от создателей TikTok. Монтаж, эффекты, переходы, субтитры и шаблоны.",
    icon: "https://upload.wikimedia.org/wikipedia/en/thumb/a/a0/CapCut_logo.svg/240px-CapCut_logo.svg.png",
    platforms: ["ios", "android"],
    rating: 4.7,
    version: "10+",
    size: "~150 МБ",
    updated: "2026",
    links: {
      ios: "https://apps.apple.com/app/capcut-video-editor/id1500855883",
      android: "https://play.google.com/store/apps/details?id=com.lemon.lvoverseas",
      official: "https://www.capcut.com"
    },
    free: true,
    popular: true
  },
  {
    id: "yandex-maps",
    name: "Яндекс Карты",
    developer: "Yandex",
    category: "navigation",
    categories: ["navigation", "popular"],
    description: "Карты, навигация, пробки, транспорт и организации.",
    fullDescription: "Яндекс Карты — подробные карты, навигация с учётом пробок, общественный транспорт, поиск организаций.",
    icon: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/80/Yandex_Maps_icon.svg/240px-Yandex_Maps_icon.svg.png",
    platforms: ["ios", "android", "web"],
    rating: 4.7,
    version: "12+",
    size: "~80 МБ",
    updated: "2026",
    links: {
      ios: "https://apps.apple.com/app/yandex-maps-and-navigator/id313877526",
      android: "https://play.google.com/store/apps/details?id=ru.yandex.yandexmaps",
      web: "https://yandex.ru/maps",
      official: "https://yandex.ru/maps"
    },
    free: true,
    popular: true
  },
  {
    id: "avito",
    name: "Авито",
    developer: "Avito",
    category: "shopping",
    categories: ["shopping", "popular"],
    description: "Объявления: купить, продать, снять, найти услуги.",
    fullDescription: "Авито — крупнейшая площадка объявлений в России. Товары, недвижимость, работа, услуги.",
    icon: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a0/Avito_logo.svg/240px-Avito_logo.svg.png",
    platforms: ["ios", "android", "web"],
    rating: 4.7,
    version: "100+",
    size: "~80 МБ",
    updated: "2026",
    links: {
      ios: "https://apps.apple.com/app/avito/id417281773",
      android: "https://play.google.com/store/apps/details?id=com.avito.android",
      web: "https://www.avito.ru",
      official: "https://www.avito.ru"
    },
    free: true,
    popular: true
  },
  {
    id: "wildberries",
    name: "Wildberries",
    developer: "Wildberries",
    category: "shopping",
    categories: ["shopping", "popular"],
    description: "Один из крупнейших маркетплейсов. Товары с доставкой.",
    fullDescription: "Wildberries — крупный онлайн-магазин. Одежда, электроника, товары для дома с доставкой.",
    icon: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1e/Wildberries_logo.svg/240px-Wildberries_logo.svg.png",
    platforms: ["ios", "android", "web"],
    rating: 4.5,
    version: "5.x",
    size: "~80 МБ",
    updated: "2026",
    links: {
      ios: "https://apps.apple.com/app/wildberries/id597880187",
      android: "https://play.google.com/store/apps/details?id=com.wildberries.ru",
      web: "https://www.wildberries.ru",
      official: "https://www.wildberries.ru"
    },
    free: true,
    popular: true
  }
];

window.APPS = APPS;
window.CATEGORIES = CATEGORIES;
